apiVersion: v1
kind: ConfigMap 
metadata: 
  name: postgres
  namespace: default 
data:
  DB_HOST: "{{ .Values.db.host }}"
  DB_NAME: "{{ .Values.db.name }}"
  DB_USER: "{{ .Values.db.user }}"
  DB_PASSWORD: "{{ .Values.db.password }}"
