---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.web.name }}-service
  labels:
    app: {{ .Values.web.name }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.targetPort }}
      targetPort: {{ .Values.web.service.containerPort }}
      name: http
  selector:
    app: {{ .Values.web.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.name }}-service
  labels:
    app: {{ .Values.api.name }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.targetPort }}
      targetPort: {{ .Values.api.service.containerPort }}
      name: http
  selector:
    app: {{ .Values.api.name }}